#!/usr/bin/env bash
# Install nginx on web server; Nginx should be listening on port 80
# Querying Nginx at its root (/) with a GET request (requesting a page)
#			curl 44.211.36.72 -> returns "Hello World!"
#			curl -sI 44.211.36.72 -> HTTP/1.1 200 OK

sudo apt-get -y update
sudo apt-get -y install nginx

mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
	listen      80 default_server;
	listen      [::]:80 default_server;
	root        /etc/nginx/html;
	index       index.html index.htm;
}
" > /etc/nginx/sites-available/default

service nginx restart
