#!/usr/bin/env bash                                                                                                                         
# Configures an Nginx server so that /redirect_me redirects to another page.                                                                
# The redirection is configured as a "301 Moved Permanently"                                                                                
                                                                                                                                            
sudo apt-get update                                                                                                                         
sudo apt-get install -y nginx                                                                                                               
                                                                                                                                            
echo "Hello World!" | sudo tee /etc/nginx/html/index.html                                                                                   
printf %s "server {                                                                                                                         
    listen 80;                                                                                                                              
    listen [::]:80 default_server;
    root   /etc/nginx/html;
    index  index.html index.htm;
                                                                                                                                            
    location /redirect_me {                                                                                                                 
        return 301 http://cuberule.com/;                                                                                                    
    }                                                                                                                                       
}" > sudo tee /etc/nginx/sites-available/default                                                                                            
                                                                                                                                            
sudo service nginx restart
