#!/usr/bin/env bash
# Bash Script displays "To infinity and beyond" indefinitely
# Displays "I am invincible!!!" when receiving a SIGTERM signal
while true
do
 echo "To infininty and beyond"
 sleep 2
 trap 'echo "I am invincible!!!"' 15
done
