#!/usr/bin/env bash
# Bash script that creates an RSA key pair.
# private key must be `school`
# bits in the created key to be created is `4096`
# created key must be protected by the passphrase `betty`
ssh-keygen -b 4096 -N betty -f school
